---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: spec/manifests
  modules_path: .kitchen-modules
  ignored_paths_from_root:
    - .kitchen
  require_chef_for_busser: false
  resolve_with_librarian_puppet: false
  require_puppet_collections: true
  puppet_debug: <%= ENV['PUPPET_DEBUG'] %>
  puppet_detailed_exitcodes: true
  retry_on_exit_code:
    - 2 # The run succeeded, and some resources were changed.
    - 6 # The run succeeded, and included both changes and failures.
  max_retries: 2
  wait_for_retry: 90

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2012r2
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2012r2
  - name: windows-2019-core
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2019-core

verifier:
  name: shell

suites:
  - name: vs2015
    excludes:
      - windows-2019-core
    provisioner:
      manifest: vs2015.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/vs2015_spec.rb
  - name: vs2015_community
    excludes:
      - windows-2019-core
    provisioner:
      manifest: vs2015_community.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/vs2015_community_spec.rb
  - name: vs2017
    excludes:
      - windows-2012r2
    provisioner:
      manifest: vs2017.pp
      max_retries: 5
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/vs2017_spec.rb
  - name: vs2019
    excludes:
      - windows-2012r2
    provisioner:
      manifest: vs2019.pp
      max_retries: 5
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/vs2019_spec.rb
  # Disabled since we currently do not deploy Build Tools 2017.
  # - name: buildtools2017
  #   provisioner:
  #     manifest: buildtools2017.pp
  #     max_retries: 1
  #     wait_for_retry: 10
  #   verifier:
  #     command: rspec -c -f d -I spec spec/acceptance/buildtools2017_spec.rb
